name: my_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_cors_headers: ^0.1.5
  postgres: ^2.3.2
  json_annotation: ^4.5.0
  build_runner: ^2.1.7
  json_serializable: ^6.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
